version: 2
updates:
  - package-ecosystem: pip
    directory: /apps/fast_api
    target-branch: feat/trunk
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest-asyncio"

  - package-ecosystem: github-actions
    directory: /
    target-branch: feat/trunk
    schedule:
      interval: monthly